### PR TITLE
Fix spelling and grammar

### LINKED ISSUE #8: Minor spelling and grammar issues in README
A few suggestions to improve the README; feel free to incorporate any of these if you'd like (or not at all):

https://github.com/jart/bestline/blob/837ea51580447d4b7fa4ffaf51e6219a820f5e11/README.md#L17

dependencies, which means

https://github.com/jart/bestline/blob/837ea51580447d4b7fa4ffaf51e6219a820f5e11/README.md#L113

diacratics &rarr; diacritics

https://github.com/jart/bestline/blob/837ea51580447d4b7fa4ffaf51e6219a820f5e11/README.md#L124

There are, however, some differences [...]

https://github.com/jart/bestline/blob/837ea51580447d4b7fa4ffaf51e6219a820f5e11/README.md#L149

"the needed" &rarr; "they needed"

### PR DESCRIPTION
**Pull request by SirDaev**
Fixes #8

### CODE REVIEW

**Review by jart — APPROVED** [review]
Thank you!

**Comment by SirDaev** [comment]
Hi! Any chance you could add the 'hacktoberfest-accepted' label to this PR?

**Comment by jart** [comment]
Done

**Comment by SirDaev** [comment]
Thanks! 😀

**Pull request merged**
