### PR TITLE
Support multi-line prompts

### PR DESCRIPTION
**Pull request by MaxGyver83**
## How to test

You can test multi-line prompts in [rc](https://github.com/rakitzis/rc) linked with _bestline_.

This branch alone isn't compatible with _rc_. But you can use my [custom](https://github.com/MaxGyver83/bestline) branch which contains some additional changes (like #33):

```sh
cd /tmp
git clone -b custom https://github.com/MaxGyver83/bestline
cd bestline
make libbestline.so
sudo cp libbestline.so /usr/local/lib/

cd ..
git clone https://github.com/rakitzis/rc
cd rc
make EDIT=bestline
./rc

fn prompt = { prompt = ($nl^`pwd^$nl^'% ' '  ') }
```

### CODE REVIEW

**Comment by jart** [comment]
Could you take a look at the changes I've made to bestline called "llama mode"? llamafile uses bestline which now supports triple quote syntax shown in this screenshot: https://www.phoronix.com/news/Llamafile-0.8.14 Does something like this help your use case?

**Comment by MaxGyver83** [comment]
> Could you take a look at the changes I've made to bestline called "llama mode"? llamafile uses bestline which now supports triple quote syntax shown in this screenshot: https://www.phoronix.com/news/Llamafile-0.8.14 Does something like this help your use case?

Thanks for your hint to "llama mode". I had a look into this. As far as I understand, this does not help here because the triple quote syntax is only for (multiline) command typed by the user. This pull request is about allowing newlines in the prompt. Bestline quits on a newline in the prompt even with llama mode activated.

**Review by jart — APPROVED** [review]
I understand now. So you want to be able to say for example:

```c
while((line = bestline("hello\nthere> ")) != NULL) { ... }
```

It's not great that when I press `CTRL-L` it discards all but the last line. However looking at the code, that would be quite ugly to remedy. So the approach you chose seems pretty reasonable. If you're happy with this, then I approve it.

Thanks!

**Review by invisiblepancake — COMMENTED** [review]
In the function bestlineEdit:

A new variable promptnotnull has been introduced to ensure the prompt is never null, defaulting to an empty string if necessary.
Another variable, promptlastnl, seeks out the final newline character within the prompt. This is a prudent measure, ensuring user prompts are handled with the utmost propriety.
The prompt used by bestlineWriteStr is now promptnotnull, which maintains the integrity of the original prompt.
Alteration in bestlineInit:

The condition has been refined to exclude newline characters from the validity check of the prompt. This change aligns with contemporary practices, ensuring the prompt's format adheres to the expected standards.

**Pull request merged**
